import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebarsReleaseNotes: SidebarsConfig = {
	releaseNotesSidebar: [
		{
			type: 'doc',
			id: 'index',
			label: 'Overview',
		},
		{
			type: 'category',
			label: 'Version 5 - Lincoln',
			link: {
				type: 'doc',
				id: 'v5-lincoln/index',
			},
			items: [{ type: 'autogenerated', dirName: 'v5-lincoln' }],
		},
		{
			type: 'category',
			label: 'Version 4 - Tucker',
			link: {
				type: 'doc',
				id: 'v4-tucker/index',
			},
			items: [{ type: 'autogenerated', dirName: 'v4-tucker' }],
		},
		{
			type: 'category',
			label: 'Version 3 - Monkey',
			link: {
				type: 'doc',
				id: 'v3-monkey/index',
			},
			items: [{ type: 'autogenerated', dirName: 'v3-monkey' }],
		},
		{
			type: 'category',
			label: 'Version 2 - Penny',
			link: {
				type: 'doc',
				id: 'v2-penny/index',
			},
			items: [{ type: 'autogenerated', dirName: 'v2-penny' }],
		},
		{
			type: 'category',
			label: 'Version 1 - Alby',
			link: {
				type: 'doc',
				id: 'v1-alby/index',
			},
			items: [{ type: 'autogenerated', dirName: 'v1-alby' }],
		},
	],
};

export default sidebarsReleaseNotes;
