import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';




const sidebarsFabric: SidebarsConfig = {
	fabricSidebar: [
		{
			type: 'doc',
			id: 'index',
			label: 'Overview',
		},
		{
			type: 'doc',
			id: 'create-account',
			label: 'Create Account',
		},
		{
			type: 'doc',
			id: 'create-organization',
			label: 'Create Organization',
		},
		{
			type: 'doc',
			id: 'organization-management',
			label: 'Organization Management',
		},
		{
			type: 'doc',
			id: 'cluster-creation-management',
			label: 'Cluster Creation & Management',
		},
		{
			type: 'doc',
			id: 'custom-domains',
			label: 'Custom Domains',
		},
		{
			type: 'doc',
			id: 'managing-applications',
			label: 'Managing Applications',
		},
		{
			type: 'doc',
			id: 'api-documentation',
			label: 'API Documentation',
		},
		{
			type: 'doc',
			id: 'database-management',
			label: 'Database Management',
		},
		{
			type: 'doc',
			id: 'logging',
			label: 'Logging',
		},
		{
			type: 'doc',
			id: 'grafana-integration',
			label: 'Grafana Integration',
		},
		// { type: 'autogenerated', dirName: 'fabric' },
	],
};




export default sidebarsFabric;



