import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
	referenceSidebar: [
		{
			type: 'doc',
			id: 'index',
			label: 'Reference',
		},
		{
			type: 'autogenerated', dirName: '.'
		}
	],
};

export default sidebars;
