import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebarsLearn: SidebarsConfig = {
	learnSidebar: [
		{
			type: 'doc',
			id: 'index',
			label: 'Welcome',
		},
		{
			type: 'category',
			label: 'Getting Started',
			collapsible: false,
			className: 'learn-category-header',
			items: [
				{
					type: 'doc',
					id: 'getting-started/install-and-connect-harper',
					label: 'Install and Connect Harper',
				},
				{
					type: 'doc',
					id: 'getting-started/create-your-first-application',
					label: 'Create your First Application',
				},
			],
		},
		{
			type: 'category',
			label: 'Developers',
			collapsible: false,
			className: 'learn-category-header',
			items: [
				{
					type: 'doc',
					id: 'developers/harper-applications-in-depth',
					label: 'Harper Applications in Depth',
				},
				{
					type: 'doc',
					id: 'developers/caching-with-harper',
					label: 'Caching with Harper',
				},
				{
					type: 'doc',
					id: 'developers/active-caching-subscriptions',
					label: 'Active Caching with Subscriptions',
				},
				{
					type: 'doc',
					id: 'developers/semantic-caching-vector-indexing',
					label: 'Semantic Caching with Vector Indexing',
				},
				{
					type: 'doc',
					id: 'developers/write-through-caching',
					label: 'Write-Through Caching',
				},
			],
		},
		{
			type: 'category',
			label: 'Administration',
			collapsible: false,
			className: 'learn-category-header',
			items: [{ type: 'autogenerated', dirName: 'administration' }],
		},
	],
};

export default sidebarsLearn;
