import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebarsLearn: SidebarsConfig = {
	learnSidebar: [
		{
			type: 'doc',
			id: 'index',
			label: 'Welcome',
		},
		{
			type: 'category',
			label: 'Getting Started',
			collapsible: false,
			className: 'learn-category-header',
			items: [
				{
					type: 'doc',
					id: 'getting-started/install-and-connect-harper',
					label: 'Install and Connect Harper',
				},
				{
					type: 'doc',
					id: 'getting-started/create-your-first-application',
					label: 'Create your First Application',
				},
				{
					type: 'doc',
					id: 'getting-started/using-agents',
					label: 'Using AI Agents',
				},
			],
		},
		{
			type: 'category',
			label: 'Developers',
			collapsible: false,
			className: 'learn-category-header',
			items: [{ type: 'autogenerated', dirName: 'developers' }],
		},
		{
			type: 'category',
			label: 'Administration',
			collapsible: false,
			className: 'learn-category-header',
			items: [{ type: 'autogenerated', dirName: 'administration' }],
		},
	],
};

export default sidebarsLearn;
